# -*- coding: utf-8 -*-
"""
Turbo Anchor Timestep Sampling — Model-agnostic

Samples timesteps from discrete anchor points generated by
FlowMatchEulerDiscreteScheduler. Used for Turbo/LCM-style
few-step distillation training.

Key features:
    - Discrete anchor points matching inference steps
    - Jittered sampling to "thicken" the flow manifold
    - Stratified sampling to reduce loss variance
    - Dynamic shift support for resolution-dependent schedule
"""

from typing import Optional, Tuple

import torch
import logging

logger = logging.getLogger(__name__)


def compute_anchors(
    num_inference_steps: int,
    shift: float = 3.0,
    num_train_timesteps: int = 1000,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Compute discrete anchor points from the FlowMatchEulerDiscreteScheduler.

    Args:
        num_inference_steps: Number of inference steps (= number of anchors)
        shift: Scheduler shift parameter
        num_train_timesteps: Total training timesteps

    Returns:
        anchor_timesteps: Discrete timesteps (N,)
        anchor_sigmas: Corresponding sigma values (N,), excluding terminal 0
    """
    from diffusers import FlowMatchEulerDiscreteScheduler

    scheduler = FlowMatchEulerDiscreteScheduler(
        num_train_timesteps=num_train_timesteps,
        shift=shift,
    )
    scheduler.set_timesteps(num_inference_steps=num_inference_steps, device="cpu")

    timesteps = scheduler.timesteps.cpu()
    sigmas = scheduler.sigmas.cpu()[:-1]  # Exclude terminal 0

    return timesteps, sigmas


def sample_anchor(
    batch_size: int,
    num_inference_steps: int = 10,
    shift: float = 3.0,
    dynamic_shift: bool = False,
    latent_shape: Optional[Tuple[int, ...]] = None,
    base_seq_len: int = 256,
    max_seq_len: int = 4096,
    base_shift: float = 0.5,
    max_shift: float = 1.15,
    jitter_scale: float = 0.02,
    stratified: bool = True,
    num_train_timesteps: int = 1000,
    min_sigma: float = 0.001,
    max_sigma: float = 0.999,
    device: torch.device = None,
    dtype: torch.dtype = None,
) -> torch.Tensor:
    """
    Sample sigmas from discrete anchor points with optional jitter.

    Args:
        batch_size: Number of samples
        num_inference_steps: Number of inference steps (= anchor count)
        shift: Fixed shift factor
        dynamic_shift: Whether to compute shift from latent_shape
        latent_shape: Latent shape for dynamic shift (B, C, H, W)
        base_seq_len: Dynamic shift base sequence length
        max_seq_len: Dynamic shift max sequence length
        base_shift: Dynamic shift base value
        max_shift: Dynamic shift max value
        jitter_scale: Standard deviation of Gaussian jitter applied to anchors
        stratified: Use stratified sampling (ensures each anchor is visited)
        num_train_timesteps: Total training timesteps
        min_sigma: Minimum sigma (clamp)
        max_sigma: Maximum sigma (clamp)
        device: Target device
        dtype: Target dtype

    Returns:
        sigmas: Sampled noise levels (B,)
    """
    if device is None:
        device = torch.device("cpu")

    # Compute effective shift
    effective_shift = shift
    if dynamic_shift and latent_shape is not None:
        from .uniform import calculate_shift
        h, w = latent_shape[-2:]
        image_seq_len = (h // 2) * (w // 2)
        effective_shift = calculate_shift(
            image_seq_len, base_seq_len, max_seq_len, base_shift, max_shift
        )

    # Compute anchor points
    _, anchor_sigmas = compute_anchors(
        num_inference_steps=num_inference_steps,
        shift=effective_shift,
        num_train_timesteps=num_train_timesteps,
    )

    n_anchors = len(anchor_sigmas)

    # Select anchor indices
    if stratified and batch_size >= n_anchors:
        # Stratified: ensure each anchor is sampled at least once
        base_indices = torch.arange(n_anchors, device=device)
        repeats = batch_size // n_anchors
        remainder = batch_size % n_anchors
        indices = torch.cat([
            base_indices.repeat(repeats),
            base_indices[torch.randperm(n_anchors, device=device)[:remainder]],
        ])
        indices = indices[torch.randperm(batch_size, device=device)]
    else:
        indices = torch.randint(0, n_anchors, (batch_size,), device=device)

    # Get base sigmas and apply jitter
    target_dtype = dtype if dtype is not None else torch.float32
    base_sigmas = anchor_sigmas.to(device=device, dtype=target_dtype)[indices]

    if jitter_scale > 0:
        jitter = torch.randn_like(base_sigmas) * jitter_scale
        sigmas = (base_sigmas + jitter).clamp(min_sigma, max_sigma)
    else:
        sigmas = base_sigmas

    return sigmas
